config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#index', as: :tasks
  post 'tasks', to: 'tasks#create'
  get 'tasks/new', to: 'tasks#new', as: :new_task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
  get 'tasks/:id', to: 'tasks#show', as: :task
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy

    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManagerHELL</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>

  <body>
    <%= yield %>

  </body>
</html>

app/views/tasks/edit.html.erb
<center><h1>Edit Task</h1>

<p><%= form_for(@task) do |f| %>
  <div class="w-50 p-3" class="form-group">
    <%= f.label :Title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="w-50 p-3" class="form-group">
    <%= f.label :Details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div></p>

  <p><%= f.submit class: 'btn btn-primary' %></p>
<% end %></center>
  <div class="dropdown-divider"></div>
<p><%= link_to "Back to list", tasks_path %></p>
</center>

app/views/tasks/index.html.erb
<center>
<h1>My Tasks</h1>
<br></br>
<% @tasks.each do |task| %>
<div class="form-check">
  <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
  <label class="form-check-label" for="defaultCheck1">
  <h5><%= link_to task.title, task_path(task) %>

    | <%= link_to task_path(task), method: :delete,
      data: { confirm: "Are you sure?" } do %>
      <i class="fas fa-trash-alt"></i>
        <% end %>
      </h5>
</label>
</div>
  <% end %>
    <div class="dropdown-divider"></div>
<p><%= link_to "Add a new task", new_task_path %></p>
</center>

app/views/tasks/new.html.erb
<center><h1>New Task</h1>

<p><%= form_for(@task) do |f| %>
  <div class="w-50 p-3" class="form-group">
    <%= f.label :Title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="w-50 p-3" class="form-group">
    <%= f.label :Details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div></p>

  <p><%= f.submit class: 'btn btn-primary' %></p>
<% end %></center>
  <div class="dropdown-divider"></div>
<p><%= link_to "Back to list", tasks_path %></p>
</center>

app/views/tasks/show.html.erb
<center>
<h1><%= @task.title %> <button type="button" class="btn btn-outline-dark" style="a:link: #000000;"><%= link_to "Edit this class", edit_task_path %></button></h1>
</center>
<center>
<div class="alert alert-warning w-25 h-25 p-3" role="alert">
<h5 align="center"><%= @task.details %></h5>
</div>

<div class="form-check">
  <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
  <label class="form-check-label" for="defaultCheck1">
  <p>This task is not completed yet</p>
</label>
</div>
  <div class="dropdown-divider"></div>
<p><%= link_to "Back to list", tasks_path %></p>
</center>